export const titles = [
  'Student',
  'Software Developer',
  'Web Developer',
  'Mobile App Developer',
  'Front-End Developer',
  'Back-End Developer',
  'Full-Stack Developer',
  'DevOps Engineer',
  'Data Scientist',
  'Data Analyst',
  'Machine Learning Engineer',
  'Artificial Intelligence Engineer',
  'Database Administrator (DBA)',
  'Systems Administrator',
  'Network Engineer',
  'Cloud Engineer',
  'Security Analyst',
  'Quality Assurance (QA) Engineer',
  'Test Automation Engineer',
  'UI/UX Designer',
  'Product Manager (Tech)',
  'Project Manager (Tech)',
  'Scrum Master',
  'Agile Coach',
  'Technical Writer',
  'IT Support Specialist',
  'IT Consultant',
  'Business Analyst (Tech)',
  'Solutions Architect',
  'Embedded Systems Engineer',
  'Hardware Engineer',
  'Firmware Engineer',
  'Game Developer',
  'AR/VR Developer',
  'Blockchain Developer',
  'Robotics Engineer',
  'Data Engineer',
  'Business Intelligence Analyst',
  'IT Manager',
  'Chief Technology Officer (CTO)',
  'Chief Information Officer (CIO)',
  'Site Reliability Engineer (SRE)',
  'User Researcher',
  'IT Trainer',
  'IT Auditor',
  'Data Privacy Officer',
  'Natural Language Processing (NLP) Engineer',
  'Computer Vision Engineer',
  'Data Engineer',
  'Edge Computing Engineer',
  'Quantum Computing Researcher',
];

export const skills = [
  'aarch64',
  'adonisjs',
  'aftereffects',
  'amazonwebservices',
  'anaconda',
  'android',
  'androidstudio',
  'angularjs',
  'ansible',
  'apache',
  'apachekafka',
  'appcelerator',
  'apple',
  'appwrite',
  'arduino',
  'argocd',
  'atom',
  'azure',
  'babel',
  'backbonejs',
  'bamboo',
  'bash',
  'behance',
  'bitbucket',
  'blender',
  'bootstrap',
  'bower',
  'bulma',
  'c',
  'cakephp',
  'canva',
  'centos',
  'ceylon',
  'chrome',
  'circleci',
  'clojure',
  'clojurescript',
  'cmake',
  'codecov',
  'codeigniter',
  'codepen',
  'coffeescript',
  'composer',
  'confluence',
  'couchdb',
  'cplusplus',
  'crystal',
  'csharp',
  'css3',
  'cucumber',
  'd3js',
  'dart',
  'debian',
  'denojs',
  'devicon',
  'digitalocean',
  'discordjs',
  'django',
  'docker',
  'doctrine',
  'dot-net',
  'dotnetcore',
  'dropwizard',
  'drupal',
  'electron',
  'eleventy',
  'elixir',
  'elm',
  'embeddedc',
  'ember',
  'erlang',
  'eslint',
  'express',
  'facebook',
  'fastapi',
  'feathersjs',
  'fedora',
  'figma',
  'filezilla',
  'firebase',
  'firefox',
  'flask',
  'flutter',
  'foundation',
  'framer',
  'fsharp',
  'gatling',
  'gatsby',
  'gcc',
  'gentoo',
  'gimp',
  'git',
  'github',
  'gitlab',
  'gitter',
  'go',
  'godot',
  'google',
  'googlecloud',
  'gradle',
  'grafana',
  'grails',
  'graphql',
  'groovy',
  'grunt',
  'gulp',
  'handlebars',
  'haskell',
  'haxe',
  'heroku',
  'html5',
  'hugo',
  'ie10',
  'ifttt',
  'illustrator',
  'inkscape',
  'intellij',
  'ionic',
  'jamstack',
  'jasmine',
  'java',
  'javascript',
  'jeet',
  'jenkins',
  'jest',
  'jetbrains',
  'jira',
  'jquery',
  'julia',
  'jupyter',
  'k3s',
  'kaggle',
  'karma',
  'knockout',
  'kotlin',
  'krakenjs',
  'kubernetes',
  'labview',
  'laravel',
  'latex',
  'less',
  'linkedin',
  'linux',
  'lua',
  'magento',
  'markdown',
  'materialui',
  'matlab',
  'maya',
  'meteor',
  'microsoftsqlserver',
  'minitab',
  'mocha',
  'modx',
  'mongodb',
  'moodle',
  'msdos',
  'mysql',
  'neo4j',
  'nestjs',
  'networkx',
  'nextjs',
  'nginx',
  'nixos',
  'nodejs',
  'nodewebkit',
  'npm',
  'nuget',
  'numpy',
  'nuxtjs',
  'objectivec',
  'ocaml',
  'openal',
  'opencv',
  'opengl',
  'opensuse',
  'opera',
  'oracle',
  'packer',
  'pandas',
  'perl',
  'phalcon',
  'phoenix',
  'photoshop',
  'php',
  'phpstorm',
  'podman',
  'polygon',
  'postgresql',
  'premierepro',
  'processing',
  'prometheus',
  'protractor',
  'putty',
  'pycharm',
  'pytest',
  'python',
  'pytorch',
  'qt',
  'r',
  'rails',
  'raspberrypi',
  'react',
  'rect',
  'redhat',
  'redis',
  'redux',
  'rocksdb',
  'rspec',
  'rstudio',
  'ruby',
  'rubymine',
  'rust',
  'safari',
  'salesforce',
  'sass',
  'scala',
  'sdl',
  'selenium',
  'sequelize',
  'shopware',
  'shotgrid',
  'sketch',
  'slack',
  'socketio',
  'solidity',
  'sourcetree',
  'spring',
  'spss',
  'sqlalchemy',
  'sqlite',
  'ssh',
  'storybook',
  'stylus',
  'subversion',
  'svelte',
  'swift',
  'symfony',
  'tailwindcss',
  'tensorflow',
  'terraform',
  'thealgorithms',
  'threejs',
  'tomcat',
  'tortoisegit',
  'towergit',
  'travis',
  'trello',
  'twitter',
  'typescript',
  'typo3',
  'ubuntu',
  'unity',
  'unix',
  'unrealengine',
  'uwsgi',
  'vagrant',
  'vim',
  'visualstudio',
  'vscode',
  'vuejs',
  'vuestorefront',
  'vuetify',
  'webflow',
  'weblate',
  'webpack',
  'webstorm',
  'windows8',
  'woocommerce',
  'wordpress',
  'xamarin',
  'xcode',
  'xd',
  'yarn',
  'yii',
  'yunohost',
  'zend',
  'zig',
];
